# - Find TrakStar SDK
# Find the native TrakStar headers and libraries.
#
#  TRAKSTAR_SDK_INCLUDE_DIRS - where to find ATC3DG.h
#  TRAKSTAR_SDK_LIBRARIES    - List of libraries when using TrakStar.
#  TRAKSTAR_SDK_BIN_DIRS     - where to find ATC3DG.dll
#  TRAKSTAR_SDK_FOUND        - True if TrakStar found.



SET(TRAKSTAR_SDK_ROOT_DIR
    "${TRAKSTAR_SDK_ROOT_DIR}"
    CACHE
    PATH
    "Root directory to search for TrakStar SDK")

# Look for the header file.
FIND_PATH(TRAKSTAR_SDK_INCLUDE_DIRS NAMES ATC3DG.h HINTS 
	"${TRAKSTAR_SDK_ROOT_DIR}/3D Guidance API" )
	
FIND_PATH(TRAKSTAR_SDK_BIN_DIRS NAMES ATC3DG.DLL HINTS 
	"${TRAKSTAR_SDK_ROOT_DIR}/3D Guidance API" )

# Look for the library.
FIND_LIBRARY(TRAKSTAR_SDK_LIBRARY NAMES ATC3DG HINTS ${TRAKSTAR_SDK_ROOT_DIR} "${TRAKSTAR_SDK_ROOT_DIR}/3D Guidance API")

MARK_AS_ADVANCED(TRAKSTAR_SDK_LIBRARY)

SET(TRAKSTAR_SDK_LIBRARIES optimized ${TRAKSTAR_SDK_LIBRARY} debug ${TRAKSTAR_SDK_LIBRARY})

# handle the QUIETLY and REQUIRED arguments and set TRAKSTAR_SDK_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TrakStarSDK DEFAULT_MSG TRAKSTAR_SDK_LIBRARIES TRAKSTAR_SDK_INCLUDE_DIRS TRAKSTAR_SDK_BIN_DIRS)

MARK_AS_ADVANCED(TRAKSTAR_SDK_LIBRARIES TRAKSTAR_SDK_INCLUDE_DIRS TRAKSTAR_SDK_BIN_DIRS)
